# Generated by Django 6.0.1 on 2026-02-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldreport',
            name='status',
            field=models.CharField(choices=[('Nouveau', 'Nouveau'), ('En cours', 'En cours de traitement'), ('Terminé', 'Terminé')], default='Nouveau', max_length=20),
        ),
        migrations.AlterField(
            model_name='fieldreport',
            name='sector',
            field=models.CharField(choices=[('Agriculture', 'Agriculture'), ('Elevage', 'Élevage'), ('Eau', 'Eau & Assainissement')], max_length=50),
        ),
    ]
