# Generated by Django 6.0.1 on 2026-02-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_fieldreport_status_alter_fieldreport_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldreport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
